### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by skandix** [skandix/.dotfiles-nix#3]
- [x] fix dotfiles theorville
- [x] edit login manager / replace
- [x] fix dotfiles
- [x] update systems
- [x] mainly use unstable and have stable for some packages
- [x] github actions for updating flake regulary
- [x] update wallpapers
    - [x] remove boring yellow ones.
- [x] tweak i3 and i3bar or setup another one like lemonbar or eww
    - [x] setup a more standarized bar, along with music being played , would be kkool
- [x] sette opp stylix https://danth.github.io/stylix/options/nixos.html for auto ricing themes
- [ ] options for gapps
- [x] edit inputs for flake
- [x] remove old generations
- [x] tweak parameters for hardware
- [x] setup auto update firmware.
- [x] consider switching from ulauncher and back to rofi or using something else
- [x] move back to zsh from fish
- [ ] helix - finish default.nix
- [ ] firefox - add in symlink of userchrome.css, for treestyletabs
- [x] Create ~/.ssh directory
- [ ] Create ~/.Pictures directory
- [ ] Create ~/.Pictures/screenshot directory
- [ ] Create ~/gitclones directory
- [ ] Create ~/junkyard directory
- [ ] Create wallpaper directory
- [x] Symlink wallpaper folder
- [ ] ....

**Comment by Mathsterk** [comment]
* ???
* profit!
